import type { User, Conversation, Message } from './types'

export const currentUser: User = {
  id: 'user-1',
  username: 'You',
  email: 'you@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=You',
  status: 'online',
}

export const mockUsers: User[] = [
  {
    id: 'user-2',
    username: 'Alice Chen',
    email: 'alice@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    status: 'online',
  },
  {
    id: 'user-3',
    username: 'Bob Smith',
    email: 'bob@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    status: 'offline',
    lastSeen: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: 'user-4',
    username: 'Carol White',
    email: 'carol@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carol',
    status: 'away',
  },
  {
    id: 'user-5',
    username: 'David Brown',
    email: 'david@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    status: 'online',
  },
  {
    id: 'user-6',
    username: 'Emma Wilson',
    email: 'emma@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    status: 'offline',
    lastSeen: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
]

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    participants: [currentUser, mockUsers[0]],
    lastMessage: {
      id: 'msg-1',
      conversationId: 'conv-1',
      senderId: 'user-2',
      content: 'Hey! How are you doing?',
      timestamp: new Date(Date.now() - 1000 * 60 * 5),
      status: 'read',
      type: 'text',
    },
    unreadCount: 2,
    isGroup: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: 'conv-2',
    participants: [currentUser, mockUsers[1]],
    lastMessage: {
      id: 'msg-2',
      conversationId: 'conv-2',
      senderId: 'user-1',
      content: 'See you tomorrow!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60),
      status: 'delivered',
      type: 'text',
    },
    unreadCount: 0,
    isGroup: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60),
  },
  {
    id: 'conv-3',
    participants: [currentUser, mockUsers[2], mockUsers[3]],
    lastMessage: {
      id: 'msg-3',
      conversationId: 'conv-3',
      senderId: 'user-4',
      content: 'Great work on the project!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
      status: 'read',
      type: 'text',
    },
    unreadCount: 0,
    isGroup: true,
    groupName: 'Project Team',
    groupAvatar: 'https://api.dicebear.com/7.x/identicon/svg?seed=ProjectTeam',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3),
  },
  {
    id: 'conv-4',
    participants: [currentUser, mockUsers[4]],
    lastMessage: {
      id: 'msg-4',
      conversationId: 'conv-4',
      senderId: 'user-6',
      content: 'Thanks for your help!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
      status: 'read',
      type: 'text',
    },
    unreadCount: 0,
    isGroup: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
]

export const mockMessages: Record<string, Message[]> = {
  'conv-1': [
    {
      id: 'msg-1-1',
      conversationId: 'conv-1',
      senderId: 'user-1',
      content: 'Hi Alice!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-1-2',
      conversationId: 'conv-1',
      senderId: 'user-2',
      content: 'Hey there! Long time no see!',
      timestamp: new Date(Date.now() - 1000 * 60 * 55),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-1-3',
      conversationId: 'conv-1',
      senderId: 'user-1',
      content: 'I know right! How have you been?',
      timestamp: new Date(Date.now() - 1000 * 60 * 50),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-1-4',
      conversationId: 'conv-1',
      senderId: 'user-2',
      content: 'Been great! Just finished a big project at work.',
      timestamp: new Date(Date.now() - 1000 * 60 * 45),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-1-5',
      conversationId: 'conv-1',
      senderId: 'user-2',
      content: 'We should catch up sometime soon!',
      timestamp: new Date(Date.now() - 1000 * 60 * 40),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-1-6',
      conversationId: 'conv-1',
      senderId: 'user-1',
      content: 'Absolutely! Coffee this weekend?',
      timestamp: new Date(Date.now() - 1000 * 60 * 30),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-1-7',
      conversationId: 'conv-1',
      senderId: 'user-2',
      content: 'Sounds perfect! Saturday works for me.',
      timestamp: new Date(Date.now() - 1000 * 60 * 10),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-1-8',
      conversationId: 'conv-1',
      senderId: 'user-2',
      content: 'Hey! How are you doing?',
      timestamp: new Date(Date.now() - 1000 * 60 * 5),
      status: 'read',
      type: 'text',
    },
  ],
  'conv-2': [
    {
      id: 'msg-2-1',
      conversationId: 'conv-2',
      senderId: 'user-3',
      content: 'Are we still on for the meeting?',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-2-2',
      conversationId: 'conv-2',
      senderId: 'user-1',
      content: 'Yes! 3pm at the usual place.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1.5),
      status: 'delivered',
      type: 'text',
    },
    {
      id: 'msg-2-3',
      conversationId: 'conv-2',
      senderId: 'user-1',
      content: 'See you tomorrow!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60),
      status: 'delivered',
      type: 'text',
    },
  ],
  'conv-3': [
    {
      id: 'msg-3-1',
      conversationId: 'conv-3',
      senderId: 'user-4',
      content: 'Everyone, the deadline has been extended!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-3-2',
      conversationId: 'conv-3',
      senderId: 'user-5',
      content: 'That is great news!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4.5),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-3-3',
      conversationId: 'conv-3',
      senderId: 'user-1',
      content: 'Perfect, more time to polish the details.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-3-4',
      conversationId: 'conv-3',
      senderId: 'user-5',
      content: 'Great work on the project!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
      status: 'read',
      type: 'text',
    },
  ],
  'conv-4': [
    {
      id: 'msg-4-1',
      conversationId: 'conv-4',
      senderId: 'user-1',
      content: 'Did you get the files I sent?',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 25),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-4-2',
      conversationId: 'conv-4',
      senderId: 'user-6',
      content: 'Yes, I did! Everything looks good.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24.5),
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg-4-3',
      conversationId: 'conv-4',
      senderId: 'user-6',
      content: 'Thanks for your help!',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
      status: 'read',
      type: 'text',
    },
  ],
}
